DROP TABLE IF EXISTS word_groups_words;
DROP TABLE IF EXISTS word_groups;
DROP TABLE IF EXISTS translation;
DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS users_telegram;
DROP TABLE IF EXISTS users;